name: Fullstack CI/CD to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${DOCKER_USERNAME}
          password: ${{ DOCKERHUB_TOKEN }}

      - name: Build and push Backend image
        uses: docker/build-push-action@v6
        with:
          context: ./back
          push: true
          tags: ${DOCKER_USERNAME}/backend:latest

      - name: Build and push Frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./front/frontend-app
          push: true
          tags: ${DOCKER_USERNAME}/frontend:latest

      - name: Deploy to EC2 Instance
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            # Login to Docker Hub on EC2
            echo "${{ DOCKERHUB_TOKEN }}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

            # Deploy Backend
            docker pull ${DOCKER_USERNAME}/backend:latest
            docker stop backend-container || true
            docker rm backend-container || true
            docker run -d --name backend-container -p 3000:3000 ${DOCKER_USERNAME}/backend:latest

            # Deploy Frontend
            docker pull ${DOCKER_USERNAME}/frontend:latest
            docker stop frontend-container || true
            docker rm frontend-container || true
            docker run -d --name frontend-container -p 80:80 ${{ DOCKER_USERNAME }}/frontend:latest